login: &login
  adapter: mysql2
  host: localhost
  encoding: utf8
  username: root
  password: root
  socket:  <%=
        ['/opt/local/var/run/mysql5/mysqld.sock', # darwinports
         '/opt/local/var/run/mysqld/mysqld.sock', # darwinports, again
         '/var/run/mysqld/mysqld.sock',           # ubuntu/debian
         '/tmp/mysql.sock'].select { |f| File.exist? f }.first %>
  min_messages: warning

development:
  database: prize_development
  <<: *login

test:
  database: prize_test
  <<: *login

production:
  database: prize
  <<: *login
